Added vue-template compiler because of build error
Ran `npm run dev`.
Got `Error: Cannot find module 'vue-template-compiler/package.json'`

Ran `npm i --save-dev vue-template-compiler`
Script worked